#include "../fonts/font3x5_1.h"
#include "rpsls.h"
#include <stdlib.h>
#include <stdbool.h>

#define MESSAGE_RATE 30
#define PACER_RATE 1000

/*Character Constants*/
static Character rock = {"ROCK", ROCK, SCISSORS, LIZARD, ROCK_BITMAP};
static Character scissors = {"SCISSORS", SCISSORS, PAPER, LIZARD, SCISSORS_BITMAP};
static Character paper = {"PAPER", PAPER, ROCK, SPOCK, PAPER_BITMAP};
static Character lizard = {"LIZARD", LIZARD, PAPER, SPOCK, LIZARD_BITMAP};
static Character spock = {"SPOCK", SPOCK, ROCK, SCISSORS, SPOCK_BITMAP};

/**Checks all directions of the navswitch for a push event
 * @return True if a push even occured
 * 			in any direction.*/
bool navswitch_event_occured_p(){
	bool event_occured = false;
	if (navswitch_push_event_p(NAVSWITCH_NORTH)){
		event_occured = true;
	}
	else if (navswitch_push_event_p (NAVSWITCH_EAST)){
		event_occured = true;
	}
	else if (navswitch_push_event_p (NAVSWITCH_SOUTH)){
		event_occured = true;
	} 
	else if (navswitch_push_event_p (NAVSWITCH_WEST)){
		event_occured = true;
	}
	else if (navswitch_push_event_p (NAVSWITCH_PUSH)){
		event_occured = true;
	}
	return event_occured;
}

/**Continuosly update sceen until a navswitch event occurs */
void navswitch_wait(void){
	navswitch_update();
	while(!navswitch_event_occured_p()){ 
		pacer_wait();
		tinygl_update();
		navswitch_update();
	}
}

/**Menu for selecting Character
 * @return The Character currently selected 
 * 			and shown on screen*/
Character selection_menu(void)
{		
	bool confirmed = false;
	uint8_t column = 0;
    uint8_t selection = 0; 
    Character options[] = {rock, paper, scissors, lizard, spock};
    
	while(!confirmed)
    {
		ledmat_display_column(options[selection].bitmap[column], column);
		column  = (column + 1) % 5;
		
		navswitch_update();
		if(navswitch_push_event_p (NAVSWITCH_NORTH)\
							|| navswitch_push_event_p (NAVSWITCH_EAST)){
			selection = WRAP5(selection + 1);
			tinygl_clear();
			tinygl_update();
		} 
		else if (navswitch_push_event_p (NAVSWITCH_SOUTH)\
							 ||navswitch_push_event_p (NAVSWITCH_WEST)){
			selection = WRAP5(selection - 1);
			tinygl_clear();
			tinygl_update();
		} 
		else if (navswitch_push_event_p (NAVSWITCH_PUSH)){
			tinygl_clear();
			tinygl_update();
			confirmed = true;
		}
	}
	return options[selection];
}

/**Get opponenent from infraredor randomly generate opponent
 * @param  Boolean value dictating single
 *          or multiplayer mode
 * @return Character chosen by opponent
 * 			or generated by computer*/
Character get_opponent(bool multi_player){
	uint8_t choice = 0;
	
	if(multi_player){
		//Do nothing at the moment
	} else {
		choice = rand() % 5;
	}
	
	switch(choice){
		case 0:
			return rock;
		case 1:
			return paper;
		case 2:
			return scissors;
		case 3:
			return lizard;
		case 4:
			return spock;
	}
	return rock;
}

/**Compares a player and opponent choice ot determine winner
 * @param 	Player's and Opponent's choices
 * @return -1 if player1 loses; 1 if player1
 *          wins; else 0 for draw*/
int8_t compare_choices(Character player1, Character player2){
	int8_t result = 0;
	if(player2.value == player1.inferior1\
					 || player2.value == player1.inferior2){
		result = 1;
	}
	else if(player1.value == player2.inferior1\
						   || player1.value == player2.inferior2){
		result = -1;
	}
	return result;
}

/**Scroll the result while the navwitch is not actioned*/
void display_result(int8_t result){    
    switch(result){
		case -1:
			tinygl_text("  LOSE!");
			break;
		case 0:
			tinygl_text("  DRAW!");
			break;
		case 1:
			tinygl_text("  WIN!");
			break;
	}
    navswitch_wait();
}


void display_opponent_choice(Character opponent){
	tinygl_point_t origin = {0,7};
	uint8_t column = 0;
	
	tinygl_text("OPPONENTS CHOICE...\0");
	navswitch_wait();	
		
	navswitch_update();
	while(!navswitch_event_occured_p()){
		ledmat_display_column(opponent.bitmap[column], column);
		column  = (column + 1) % 5;
		navswitch_update();
	}
	tinygl_clear();
	tinygl_update();
}

bool game_mode_selection(void){
	bool confirmed = false;
	bool multiplayer = false;
	tinygl_text("SINGLE PLAYER");
	
	while(!confirmed){
		pacer_wait();
		navswitch_update();
		if(navswitch_push_event_p (NAVSWITCH_NORTH)\
							|| navswitch_push_event_p (NAVSWITCH_EAST)){
			if(multiplayer == true){
				tinygl_text("  SINGLE PLAYER");
				multiplayer = false;
			}
		} 
		else if (navswitch_push_event_p (NAVSWITCH_SOUTH)\
							 ||navswitch_push_event_p (NAVSWITCH_WEST)){
			if(multiplayer == false){
				tinygl_text("  TWO PLAYER");
				multiplayer = true;
			}
		} 
		else if (navswitch_push_event_p (NAVSWITCH_PUSH)){
			tinygl_clear();
			tinygl_update();
			confirmed = true;
		}
		tinygl_update();
	}
	return multiplayer;
}
/** Main game loop.*/
void play_game(void)
{    
	Character player;
	Character opponent;
	
	bool multiplayer = false;
	int8_t result = 0;
	uint8_t player_score = 0;
	uint8_t opponent_score = 0;
	
	tinygl_text("ROCK PAPER SCISSORS LIZARD SPOCK");
	navswitch_wait();
	
	multiplayer = game_mode_selection();
	
	while(player_score < 3 && opponent_score < 3){
		player = selection_menu();
		opponent = get_opponent(multiplayer);
		result = compare_choices(player, opponent);
		
		if(result == 1){
			player_score += 1; 
		} 
		else if (result == -1) {
			opponent_score -= 1;
		}
		display_opponent_choice(opponent);
		display_result(result);
    }
    
    if(player_score == 3){
		tinygl_text("  YOU WIN!");
	} else {
		tinygl_text("  YOU LOSE!");
	}
	navswitch_wait();
	tinygl_clear();
	tinygl_update();
}

int main (void)
{
	//initialise
    system_init ();
    ledmat_init();
    navswitch_init();
    pacer_init(PACER_RATE);
    tinygl_init(PACER_RATE);
    
    tinygl_font_set (&font3x5_1);
    tinygl_text_mode_set (TINYGL_TEXT_MODE_SCROLL);
    tinygl_text_dir_set (TINYGL_TEXT_DIR_ROTATE);
    tinygl_text_speed_set (MESSAGE_RATE);
	
	//Game loop
	while(1){
		play_game();
	}
    
    return 0; 
}
